# Welcome to Jekyll!
#
# Site settings
title: Resume for Frederik Martens
name: Frederik Martens
description: Frederik Martens - Resume, Curriculum Vitae, CV
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
#markdown: kramdown
